name: Grachev Homeworkflow

on:
  push:
    branches: 
      - master

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.7.0
      uses: actions/setup-node@v1
      with:
        node-version: '18.7.0'
    - name: Check linters
      run: |
        npm i
        npm run lint
      env:
        CI: true
   
  docker:
    runs-on: ubuntu-latest
    needs: linters
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.7.0
      uses: actions/setup-node@v1
      with:
        node-version: '18.7.0'
    - name: Create Docker image
      run: |
        docker build -t image_name .
      env:
        CI: true
   
   
   
     